---

- name: Restart taskd service
  become: true
  service:
    name: taskd
    enabled: true
    daemon_reload: true
    state: restarted
  listen: taskd restart service

- name: Restart taskwarrior-sync timer
  become: true
  service:
    name: taskwarrior-sync.timer
    enabled: true
    daemon_reload: true
    state: restarted
  listen: taskd restart sync timer
